### PR TITLE
Provide phoenicis.sh for Java 8 and Java 10+

### LINKED ISSUE #1408: phoenicis.sh must be different for Java 8 and 10/11
For Java 10/11, run with:
```
java -cp 'phoenicis-dist/target/lib/*':phoenicis-dist/target/phoenicis-dist-5.0-SNAPSHOT.jar -p /<path>/javafx-sdk-11/lib --add-modules javafx.controls org.phoenicis.javafx.JavaFXApplication
```

How can we handle this?

### PR DESCRIPTION
**Pull request by plata**
fixes #1408

### CODE REVIEW

**Comment by madoar** [comment]
Is it possible to add a java version check to the shellscript to prevent the need of two different launcher files?

**Comment by plata** [comment]
I wanted to do that originally but the file is not copied in the pom but from the assembly plugin. Check #1485.

**Comment by madoar** [comment]
Ah, I forgot that.
Just to recap: It is currently the case, that the required end-user java version depends on the java version used to build the jar?

**Comment by plata** [comment]
Yes, but that's normal. You cannot run anything built for Java 10 with Java 8 (the other way around should work). In our case we have the additional issue with JavaFX.

**Comment by madoar** [comment]
This adds the question: which JDK do we use to build our release version?

**Comment by plata** [comment]
The default for the target system. So Java 8 for Ubuntu 16.04, Java 10 for Ubuntu 18.04, Java 11 for flatpak etc.

**Comment by plata** [comment]
@madoar is there anything left that should be done for this PR?

**Comment by plata** [comment]
I fully agree with that.

**Pull request merged**
