### PR TITLE
Test .deb

### LINKED ISSUE #1297: Test .deb in Travis

### PR DESCRIPTION
**Pull request by plata**
fixes #1297

### CODE REVIEW

**Comment by plata** [comment]
The caching does not seem to work. I have no idea why.

**Comment by madoar** [comment]
I'm not too sure I understand what exactly travis should execute via this script.

What exactly are you caching?

**Comment by madoar** [comment]
Can we maybe use docker for this instead?
I mean we could just use an ubuntu docker container, in which we execute the `.deb` file and the final application.
What do you think?

**Comment by plata** [comment]
The problem is not the execution. The problem is that the .deb is not available in the cache. I've contacted Travis regarding this but they couldn't find a solution yet as well (it's working in a smaller test setup).

**Comment by plata** [comment]
The caching works now but the installation does not (unmet dependencies).

**Comment by plata** [comment]
I'm now using a docker container with Ubuntu 16.04 to install the .deb. That's working. @madoar @qparis anything else we can/should test here?

**Comment by madoar** [comment]
I'm fine with this PR.

The only suggestion I have is to use a Dockerfile, instead of adding the commands directly to the travis configuration.
The benefit when using a Dockerfile is, that we can execute the image/container locally, instead of only being dependent on travis to execute it.

**Comment by plata** [comment]
What should be in that Dockerfile? The .deb test currently only calls `apt install`.

**Comment by plata** [comment]
To be honest, I don't quite get what you have in mind. Feel free to provide a PR with your idea.

**Pull request merged**
