### PR TITLE
JavaFX: simple/advanced mode

### PR DESCRIPTION
**Pull request by plata**
Library
Settings

### CODE REVIEW

**Comment by plata** [comment]
@Gcenx do you think this would be good for macOS users?

**Comment by Gcenx** [comment]
@plata seems fine

As I'm not familiar with JavaFX this is more a question, usually you want your application to match the system theming by default but can be overridden by the user.

**Comment by plata** [comment]
We have different seems (e.g. for KDE Breeze). It's not selected by default but you can choose it in the settings. Currently, there's nothing for Mac OS but it should not be too difficult to create a matching theme for it.

**Comment by plata** [comment]
@madoar I would like to hear your opinion regarding this as well.

**Comment by madoar** [comment]
Can you explain a bit more which features you want to place in the `advanced mode` and which in the `simple mode`?

In my opinion the details panel looks a bit strange without the detail information shown. Especially the `edit` button feels out of place to me.

**Comment by plata** [comment]
- Simple mode: only the very basic functionality to install/uninstall and run an app + settings.
- Advanced mode: everything else

I wasn't quite sure about the edit button. I mainly kept it because you can also edit the command line arguments e.g. in Steam. However, I'm fine removing it if you prefer that.

**Comment by madoar** [comment]
In my opinion it depends on whether the user is able to create new shortcuts in the `simple mode`. If he is able to create new shortcuts he should also be able to modify and delete them.

**Comment by plata** [comment]
He's not (in my opinion).

**Comment by madoar** [comment]
Then I think we should remove both the `delete` (of shortcuts) and the `edit` functionality.

**Comment by plata** [comment]
We need the delete because otherwise you cannot uninstall any app.

**Comment by madoar** [comment]
Yes, but we should ensure that the user can not accidentally delete the shortcut without removing the container because (s)he will not be able to remove the container afterwards without a working shortcut and entering advanced mode.

**Comment by madoar** [comment]
Does the change between `simple mode` and `advanced mode` require a restart of the application?

**Comment by plata** [comment]
That's not quite correct. You could have a situation where multiple apps share a container. So yes, there might be situations where you get a dangling container. However, I would suggest to wait if this is really something that happens in reality before deciding what to do about it.

**Comment by plata** [comment]
Restart is required (e.g. the engines tab cannot be added/removed on the fly). At least currently.

**Comment by plata** [comment]
@madoar can I merge this?

**Comment by madoar** [comment]
I guess we can go with this change, but I'm kind of missing "repair" functionality in case an installation script fails. I think this will be the case more often than we expect, at least while the application is still in alpha/beta. Additionally it is still not really clear to me which functionality should be part of the `simple mode` and which of the `advanced mode`. Ideally we should specify this before we perform the split otherwise I'm almost certain that we won't move wrongly placed functionality later on.

**Comment by plata** [comment]
Ok. I will merge this so that we have a basic working implementation. Can you open an issue/issues for the points you would like to discuss?

**Pull request merged**
