### PR TITLE
Travis: build with JDK 12

### PR DESCRIPTION
**Pull request by plata**
- add OpenJDK 11
- remove Oracle JDK support
- use OpenJDK 12 for Flatpak

see #1960

### CODE REVIEW

**Comment by plata** [comment]
Do you see any reason to maintain Oracle JDK support?

**Comment by madoar** [comment]
If it is easy to retain I would suggest retaining it. I agree that OpenJDK is the most important one to test. So if it takes too much effort to maintain OracleJDK support in travis we can remove.

**Comment by plata** [comment]
At least it didn't seem like OracleJDK 12 is available/works.

**Comment by plata** [comment]
@qparis are you ok with removing OracleJDK support as well?

**Comment by qparis** [comment]
Yes

**Comment by qparis** [comment]
Did you manage to run the project with OpenJDK 12?

**Comment by plata** [comment]
Didn't try that yet. Just wanted to prepare the Travis part so that we have the build already. You are right, I should have checked for the flatpak. So blame me if I broke it.

**Comment by qparis** [comment]
I suspect it is broken with Java 12

**Comment by plata** [comment]
Ok, I will revert the flatpak change and separate it to a new pr. Should have done this anyways...

**Comment by plata** [comment]
However, this also indicates that our tests are not really good enough.

**Pull request merged**
