### PR TITLE
Fix "engine" written twice

### PR DESCRIPTION
**Pull request by omeritzics**
In string [#2334](https://crowdin.com/translate/phoenicis/3/en#2334)
––––––––––
Off-topic: Hebrew is 100% now. May you review the translations and add them to the official release, please?

### CODE REVIEW

**Comment by plata** [comment]
This should be fixed in the source file (the `.pot` is generated).

**Comment by omeritzics** [comment]
> This should be fixed in the source file (the `.pot` is generated).

Thank you, now I fixed it in the source file.

**Review by plata — APPROVED** [review]

**Comment by plata** [comment]
Thanks for the fix.

I will look at the translations. However, I cannot promise when I will manage to do so.

**Comment by omeritzics** [comment]
Thank you

**Pull request merged**
