### PR TITLE
Add GitHub action to update translations

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
I'm not really sure about the part which avoids commits if only the date changed.

**Comment by madoar** [comment]
Can we check whether it works as intended by changing the job to trigger on every push?

**Comment by plata** [comment]
Doesn't look as expected but no commit either.

**Comment by madoar** [comment]
It seems like `Run Maven` stumbles across an error:

```
[INFO] Processing pt.po
Error:  Could not execute msgcat.
org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
    at org.codehaus.plexus.util.cli.Commandline.execute (Commandline.java:697)
    ....
```

**Comment by plata** [comment]
Ah thanks. Didn't see that one. Why doesn't it fail in this case?

**Comment by plata** [comment]
I still don't quite understand why we got a different order in the `keys.pot` compared to Travis. But that should be only once. So I think we can merge this.

**Review by madoar — APPROVED** [review]

**Pull request merged**
