### PR TITLE
Build self-contained .jar for JavaFX application

### PR DESCRIPTION
**Pull request by plata**
Uses [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) to build a .jar in `phoenicis-javafx/target/jfx/app`. This can be started simply with `java -jar`.

Might also be useful for snap/flatpak.

### CODE REVIEW

**Comment by madoar** [comment]
The plugin seems to have some problems in combination with Java 9

**Comment by plata** [comment]
For whatever reason, it cannot find javafxpackager.

**Comment by plata** [comment]
@FibreFoX any hints what could be the problem?

**Comment by FibreFoX** [comment]
@plata the javafx-maven-plugin is not compatible with that JDK version, in the current state there is only proper support for JDK 8, but you might want to check using the somewhat dusty SNAPSHOT-version `8.9.0-SNAPSHOT` of the plugin.

One of the problem was the changed location of `ant-javafx.jar` file, in JDK 10 this became a lot of harder (because the classes were packaged in the new `jmod`-thing. (Getting even absurd with JDK 11 because it's not bundled within the OracleJDK anymore).

**Comment by plata** [comment]
@FibreFoX Thanks for the info. Any idea about bundling only JRE/JFX without using a native bundler (I'd like to use this for flatpak).

**Comment by FibreFoX** [comment]
@plata I'm not sure I understood that correctly, so you want to just have the package bundled like calling `mvn jfx:jar`, right? Then you have several options:
* You might be able to change the dependency inside the plugin, but this has to be done via maven profiles (the ugly way, because inside plugins, exclusions aren't working that easy, https://issues.apache.org/jira/browse/MNG-2163).
* You might want to try using the SNAPSHOT-version (recommended), as this has this done already.
* Use a different maven-plugin which does this all.

**Comment by plata** [comment]
@FibreFoX yes, like `mvn jfx:jar` just with an JRE which I can bundle. Can you suggest a plugin which does this? I've searched quite a bit on the Internet but didn't find anything.

**Comment by FibreFoX** [comment]
Before doing more suggestions:
* So do you need a stripped down JRE (using jlink)?
* Do you need any native launcher?
* Why even switching from `javafx-maven-plugin`? Calling `mvn jfx:jar` with the SNAPSHOT-version should work without any need to change a lot.

Because JDK 9 was only a small intermediate release (oracle changed their release-cycle), please avoid using JDK 9 any more, if possible directly switch to JDK 10.

**Comment by plata** [comment]
@FibreFoX so it seems to be working with the snapshot version. However, I don't get the jlink part. Can I execute it with `javafx-maven-plugin` or do I need something additional like `maven-jlink-plugin`?

**Pull request closed without merging**
