### PR TITLE
Auto merge dependabot PRs

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by madoar** [comment]
Isn't there a configuration setting in dependabot for this?

**Comment by plata** [comment]
No. There's an issue about it somewhere (can't find it now). Basically it's a decision by GitHub that you this shall not be possible.

**Review by madoar — APPROVED** [review]

**Comment by plata** [comment]
> Job has been terminated due to insufficient credits balance

what?

**Comment by madoar** [comment]
> > Job has been terminated due to insufficient credits balance
> 
> what?

Where did you get that message?

**Comment by plata** [comment]
in Travis

**Pull request merged**
