### PR TITLE
Extract button css to buttons.less

### PR DESCRIPTION
**Pull request by madoar**
This PR addresses the first task of #1800 by splitting the themes into a `buttons.less` and `main.less` file.
I'm currently not sure whether we should use a flat or nested hierarchy for the button css.

### CODE REVIEW

**Comment by plata** [comment]
Wouldn't it be better to group by tab/functionality? In other applications, it makes a lot of sense to group by type but in Phoenicis, many styles depend more on the place where they are used than the type of the control.

**Comment by madoar** [comment]
Yes, this was what I meant by the second step of #1800 :D
The idea was to first extract the images, this makes it easier in my opinion to change the visuals of our buttons. Afterwards I want to overhaul the remaining css according to their functionality/tab.
It is likely that this second step will be combined with #1491.

I'm still open for ideas, because I currently only have a very loose plan, which will likely require some later refinement.

**Comment by plata** [comment]
If we use general.less, apps.less, containers.less etc. later, why introduce buttons.less now?

**Comment by madoar** [comment]
It seems like I misunderstood you. So basically you want to split the main.less file into multiple files according to the targeted functionality?

Either way I think we should continue the discussion in #1800 and let this PR stay open until we have decided how to continue.

**Comment by madoar** [comment]
I don't think that we should go with the approach in this PR anymore. I agree with @plata that it is a better idea to split the styles according to the targeted functionalities, e.g.:

- library
- applications
- container
- engines
- ...

**Comment by plata** [comment]
Do we have an issue to track that we want to do this?

**Pull request closed without merging**
