### PR TITLE
Enhance documentation for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by qparis**
This is a treacherous issue. 

On Java 10, the following VM options run fine: 
* --add-modules=ALL-MODULE-PATH --module-path=phoenicis-dist/target/lib
OR 
* --add-modules=java.base,javafx.base,javafx.media,javafx.graphics,javafx.controls,java.naming,java.sql --module-path=phoenicis-dist/target/lib

On Java 11, you need to remove the "=" after --module-path. Otherwise, you are likely to get the following error: 

```
Caused by: java.lang.IllegalAccessError: class javafx.scene.control.Tab (in unnamed module @0x779da8c8) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x779da8c8
	at javafx.scene.control.Tab.<init>(Tab.java:820)
	at javafx.scene.control.Tab.<init>(Tab.java:100)
	at org.phoenicis.javafx.views.mainwindow.ui.MainWindowView.<init>(MainWindowView.java:62)
	at org.phoenicis.javafx.views.mainwindow.library.LibraryView.<init>(LibraryView.java:73)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary.viewLibrary(ViewsConfigurationLibrary.java:53)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$8d4ee5c5.CGLIB$viewLibrary$0(<generated>)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$8d4ee5c5$$FastClassBySpringCGLIB$$5a713a57.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$8d4ee5c5.viewLibrary(<generated>)
	at org.phoenicis.javafx.views.ViewsConfiguration.viewLibrary(ViewsConfiguration.java:114)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$3dca612.CGLIB$viewLibrary$3(<generated>)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$3dca612$$FastClassBySpringCGLIB$$3778cf1d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$3dca612.viewLibrary(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 69 more

Process finished with exit code 0

```

or 

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
```

### CODE REVIEW

**Comment by qparis** [comment]
How can we restart the build?

**Comment by plata** [comment]
There should be a button in the "Checks" tab.

**Comment by qparis** [comment]
Any way, my last PR starts from this merge request and pass. I think we can merge both safely

**Comment by plata** [comment]
I don't know what's wrong with the Travis build. Just merge it.

**Comment by plata** [comment]
Now you can delete this PR because the change has already been merged with the other one.

**Pull request closed without merging**
