### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by plata**
Enjoy!

### CODE REVIEW

**Comment by plata** [comment]
We need some strategy how we want to handle translations in the future. Do we want to merge the updates as soon as something changes or do we want to collect updates first?

Also: currently translations are updated whenever someone changes them. Is this ok for us or do we want to use the review process inside Crowdin to ensure a certain quality of the translations?

**Comment by madoar** [comment]
- I think we should merge translation PRs as soon as possible, because I think they're prone to merge conflicts, when other changes are done to the source code.
- To ensure the correctness of the translations, I believe it's easier to use the review process inside Crowdin, than to do this in GitHub.

**Comment by plata** [comment]
Agreed.

I've changed the settings in Crowdin. However, this now implies that the translations must be approved. Can you check and approve the German translations?

**Comment by madoar** [comment]
Does Crowdin send an email, when a new translation has been submitted?
If this is the case I can take a look at them.

**Comment by plata** [comment]
I think you can configure it in the [notifications](https://support.crowdin.com/advanced-project-setup/#notifications).

**Pull request merged**
