### PR TITLE
Checkstyle action (reviewdog)

### PR DESCRIPTION
**Pull request by plata**
Codacy does not work reliably lately and the configuration is more difficult compared to GitHub actions.

### CODE REVIEW

**Comment by plata** [comment]
Codacy didn't even complain when it was wrong.

**Comment by plata** [comment]
Yes.

This PR needs an update after the next version of the checkstyle action has been released (such that the action actually fails if it detects an error).

**Comment by madoar** [comment]
@plata any news regarding this PR?

**Comment by plata** [comment]
Should be good now, I think.

**Comment by madoar** [comment]
Now the question is: does it work as intended?

**Comment by plata** [comment]
We will only find out by keeping the GitHub action and Codacy for some time in parallel.

**Comment by madoar** [comment]
Ok feel free to merge when you think the PR is ready :)

**Comment by plata** [comment]
Can you approve?

**Review by madoar — APPROVED** [review]

**Pull request merged**
