### PR TITLE
CLI: fix app installation

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
Two things we should do after merging this:
- Unify the code with `ApplicationInformationPanelSkin`.
- Change `getType` etc. to use only the ID. As this has an impact on the scripts, we should maybe postpone it until after the next release.

**Comment by madoar** [comment]
This PR has a merge conflict.

How do you want to track the TODOs?

**Comment by plata** [comment]
I will create new issues for the TODOs.

**Comment by plata** [comment]
@madoar could you review this?

**Pull request merged**
