### PR TITLE
use GitHub Pages for documentation

### PR DESCRIPTION
**Pull request by plata**
GitHub Pages have some advantages compared to the wiki, e.g.:
* Documentation can be updated with pull requests so anybody can contribute.
* Better tables of content

How it looks like:
https://plata.github.io/POL-POM-5/

### CODE REVIEW

**Comment by madoar** [comment]
This looks quite nice.
I have a few questions:
- how is the html code generated?
- where do you suggest to host the github pages (i.e. in a docs folder or on a new branch)?
- how do we build the pages (I guess with travis)?

**Comment by plata** [comment]
* The HTML is generated by GitHub Pages internally (via Jekyll).
* The pages are stored in the "docs" folder.
* Do you want to use Travis to check pull requests for the pages? I'm not sure if that's possible. However, the pages are written in Markdown so the standard GitHub preview should be enough to show the differences and whether or not it will work.

**Comment by madoar** [comment]
I think we can go with this, what do you think @qparis?

**Comment by plata** [comment]
Travis checks are also working now, so ok to merge from my side.

**Comment by plata** [comment]
@qparis please tell if we want to use this or not. If yes, I will also do it for the Scripts repository.

**Comment by plata** [comment]
Do you know if the wiki will be deleted if I uncheck it in the settings?

**Pull request merged**
