### PR TITLE
Update flatpak

### PR DESCRIPTION
**Pull request by plata**
- use name `org.phoenicis.playonlinux`
- update appdata.xml according to flathub requirements

### CODE REVIEW

**Comment by plata** [comment]
@qparis shall I merge this as is or do you want to upload the screenshot on our server?

**Comment by qparis** [comment]
What do you think is best?

**Comment by plata** [comment]
I don't know. It might be perceived as cleaner on our server.

**Comment by plata** [comment]
But if it's too much work, I can just use the GitHub image. I don't want to distract you from the deb.

**Comment by qparis** [comment]
We need to think someday about how you can have access to the servers, or at least some of them

**Comment by plata** [comment]
We can think about that. So I use the GitHub image for now?

**Comment by qparis** [comment]
If you can change it easily later, yes

**Comment by qparis** [comment]
I have some blocker bugs I need to fix on macOS

**Comment by plata** [comment]
Don't worry. Shouldn't be a problem to update it later.

**Pull request merged**
