### PR TITLE
Fix bug tracker url type

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by plata** [comment]
Shall we set the forum for type `help`?

**Comment by AsciiWolf** [comment]
@plata The "help" type should be used for "online user's reference, a software manual or help page", as noted [here](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html). ;-)

**Comment by plata** [comment]
Understood. Do you think it makes sense to point help to https://phoenicisorg.github.io/phoenicis/?

**Comment by AsciiWolf** [comment]
Yup, that looks reasonable. :-)

**Comment by plata** [comment]
Would you mind providing a pull request for it?

**Pull request merged**
