### PR TITLE
Travis: create GitHub releases

### PR DESCRIPTION
**Pull request by plata**
- nightly release from master
- "real" release for tags

I'm not sure how to test this before merging.

### CODE REVIEW

**Review by madoar — CHANGES_REQUESTED** [review]
(Credential-)Tokens should not be added in a hardcoded way in configuration files in the repository. Please add them as secrets under the repository settings instead.

**Comment by plata** [comment]
I followed https://docs.travis-ci.com/user/deployment-v2/providers/releases/.

**Review by madoar — APPROVED** [review]
Ah, ok so it is not an universally usable token. It is bound to a user/service?

**Comment by plata** [comment]
My understanding is that it's bound to the Phoenicis Bot.

**Comment by madoar** [comment]
Do we still require this PR after merging the Github Action PRs?

**Comment by plata** [comment]
No.

**Pull request closed without merging**
