### PR TITLE
Allow to create graal.js engine in PhoenicisScriptEngineFactory 

### PR DESCRIPTION
**Pull request by plata**
```Java
new ScriptEngineManager().getEngineByName(type.toString())
```
doesn't work like expected for "graal.js". When I debug, I see that it calls `NashornScriptEngineFactory` and cannot find the `ScriptEngine`. Any ideas?

### CODE REVIEW

**Comment by madoar** [comment]
Have you tried updating the used version of `graal.js`? Maybe that fixes the problem.

**Comment by plata** [comment]
You mean this: https://github.com/PhoenicisOrg/phoenicis/blob/d0ec44afbcd5431e794a17f46f3b604c753686f8/pom.xml#L86? Seems to be the latest.

**Comment by madoar** [comment]
Then I think we have found the reason. I think we need all dependencies located in: https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/master/pom.xml

**Comment by plata** [comment]
Just found that as well. Do you think we should add the runtime dependencies as well? I don't think they are required.

**Comment by madoar** [comment]
Maybe the profiler, but I think they are required for their benchmark and not to run graaljs.

**Comment by plata** [comment]
Still the same behavior.

**Comment by madoar** [comment]
Does https://github.com/graalvm/graal-js-jdk11-maven-demo compile and run on your PC?

**Comment by plata** [comment]
No, I get package "org.graalvm.polyglot does not exist". Do I have to install something manually? I thought it's all in Maven?

**Comment by madoar** [comment]
It should be all maven.

**Comment by plata** [comment]
Forget it, my JAVA_HOME wasn't set properly.

**Comment by plata** [comment]
So yes, this example works.

**Comment by madoar** [comment]
Have you tried adding all dependencies to our pom.xml?

**Comment by plata** [comment]
Yes. I'm not sure if we need this compiler.jar stuff.

**Comment by madoar** [comment]
I think for now it is ok to have more dependencies than are required, as long as it works.
We should just watch out to remove the unnecessary dependencies before we merge the graal branch in the master branch.

**Comment by plata** [comment]
It still doesn't work.

**Comment by madoar** [comment]
Hmmm, is there a difference between how the graal.js demo and our application accesses the engine?

**Comment by plata** [comment]
I don't think so. They also use
```Java
ScriptEngine graaljsEngine = new ScriptEngineManager().getEngineByName("graal.js");
```

**Comment by plata** [comment]
I've tried to set the command line options as in the example and also here: https://github.com/graalvm/graaljs/issues/17. However, no success either.

I'm a bit out of ideas currently.

**Comment by madoar** [comment]
I think you're missing the java arguments:

```xml
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <id>default-cli</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <arguments>
                                        <argument>--module-path</argument>
                                        <!-- automatically creates the modulepath using all project dependencies, also adding the project build directory -->
                                        <modulepath/>
                                        <argument>-classpath</argument>
                                        <!-- automatically creates the classpath using all project dependencies, also adding the project build directory -->
                                        <classpath/>
                                        <argument>-XX:+UnlockExperimentalVMOptions</argument>
                                        <argument>-XX:+EnableJVMCI</argument>
                                        <argument>--upgrade-module-path=${compiler.dir}/compiler.jar</argument>
                                        <argument>com.mycompany.app.App</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>nograal</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <arguments>
                                        <argument>--module-path</argument>
                                        <!-- automatically creates the modulepath using all project dependencies, also adding the project build directory -->
                                        <modulepath/>
                                        <argument>-classpath</argument>
                                        <!-- automatically creates the classpath using all project dependencies, also adding the project build directory -->
                                        <classpath/>
                                        <argument>com.mycompany.app.App</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <executable>${JAVA_HOME}/bin/java</executable>
                        </configuration>
                    </plugin>
```

What we want to execute is the `default-cli` execution I think.
If we use `nograal`, we will execute the application with nashorn I think.

**Comment by plata** [comment]
I had added those options in IntelliJ. From my understanding, they should only speed up graal. In any case, it didn't help.

**Comment by plata** [comment]
Can you try if it works on your machine?

**Comment by madoar** [comment]
When I try to execute a script with this PR (install Notepad++), I get a null pointer exception:

```
Exception in thread "pool-3-thread-1" org.phoenicis.scripts.interpreter.ScriptException: java.lang.NullPointerException
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngine.handleError(PhoenicisScriptEngine.java:74)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngine.eval(PhoenicisScriptEngine.java:39)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.builtins.ScriptUtilitiesInjector.injectInto(ScriptUtilitiesInjector.java:13)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngineFactory.lambda$createEngine$0(PhoenicisScriptEngineFactory.java:39)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngineFactory.createEngine(PhoenicisScriptEngineFactory.java:39)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngine.eval(PhoenicisScriptEngine.java:37)
	... 9 more
```

**Comment by plata** [comment]
Ok, but that's the next step. The `ScriptEngine` is created now. I had added the dependencies to `<dependencyManagement>` ...

**Comment by madoar** [comment]
Ok, after merging your latest 3 commits I can start the Notepad++ installation.
After clicking on "Next" I get the following error message in an `ErrorDialog`:

```
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: INVOKE on JavaObject[com.oracle.truffle.js.javaadapters.org.phoenicis.engines.Engine@7abc6fb3 (com.oracle.truffle.js.javaadapters.org.phoenicis.engines.Engine)] failed due to: java.lang.ClassCastException: Cannot convert '(0) []'(language: JavaScript, type: Array) to Java type 'java.lang.String': Unsupported target type.
	at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:207)
	at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:179)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngine.eval(PhoenicisScriptEngine.java:50)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: INVOKE on JavaObject[com.oracle.truffle.js.javaadapters.org.phoenicis.engines.Engine@7abc6fb3 (com.oracle.truffle.js.javaadapters.org.phoenicis.engines.Engine)] failed due to: java.lang.ClassCastException: Cannot convert '(0) []'(language: JavaScript, type: Array) to Java type 'java.lang.String': Unsupported target type.
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:358)
	at com.oracle.truffle.js.javaadapters.org.phoenicis.scripts.Installer.run(Unknown Source)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:335)
	at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:205)
	... 8 more
```

**Comment by plata** [comment]
I think we should merge this PR because the scope is only to create the `ScriptEngine` object for graal. Then we can continue on the "graalvm" branch.

**Pull request merged**
