### PR TITLE
Flatpak: use OpenJDK 12

### PR DESCRIPTION
**Pull request by plata**
TODO: test if it works

### CODE REVIEW

**Comment by qparis** [comment]
Now it should work

**Comment by madoar** [comment]
@plata any news about this? :)

**Comment by plata** [comment]
I didn't check. However, https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk is using Java 13 by now. I think it makes sense to stick to the LTS versions for the flatpak. Therefore I would suggest to close this.

**Comment by madoar** [comment]
Ok then let us close this

**Pull request closed without merging**
