### PR TITLE
Remove the dependencies to com.sun.javafx.collections

### LINKED ISSUE #1472: Implement PhoenicisFilteredList without com.sun.javafx.collections
The implementation of `PhoenicisFilteredList` must be changed such that it doesn't use `com.sun.javafx.collections` (see [here](https://stackoverflow.com/questions/48171380/com-sun-javafx-collections-in-java-9)).

We can currently circumvent the issue by `--add-exports` but that might change in the future.

### PR DESCRIPTION
**Pull request by madoar**
This PR removes the dependencies to `com.sun.javafx.collections` from inside the `PhoenicisFilteredList` class and fixes #1472.
Please be sure to test it locally first before we merge it, it is working correctly for me but just to be sure...

### CODE REVIEW

**Comment by plata** [comment]
@madoar the Travis .deb test is failing. Can you merge master, that might solve it already?

**Comment by plata** [comment]
Why does this now show the updated dependencies in the diff?

**Comment by madoar** [comment]
I did a `rebase`, I guess github interprets it differently than I

**Comment by plata** [comment]
I guess you need to merge.

**Comment by plata** [comment]
Looks better now. The Travis .deb error is strange. I don't think it is related in any way to your change. Can you verify that the .deb is still built locally?

**Comment by madoar** [comment]
Ok, it seems like no `.deb` file is built...
I tried it on the master branch.

**Comment by plata** [comment]
Yeah it's because I've disabled the .deb build for Java 8.

**Pull request merged**
