### PR TITLE
Update release process documentation

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
@qparis please check if this matches what has to be done.

**Comment by qparis** [comment]
Really harder for these reasons:
* It needs hdiutil tool available only on macOS (so impossible to run on our own servers) 
* .app must be signed before the dmg is built (I think this is the hardest part) 
* compiled binaries need to be added inside the package.

**Comment by plata** [comment]
Do you want to detail the .dmg build? Feel free to edit the .md directly.

**Comment by qparis** [comment]
I can but the _compiled binaries need to be added inside the package._ is really artisanal :-D

**Comment by plata** [comment]
Maybe we should better have a separate documentation page for that. It will probably overload this page.

**Pull request merged**
